server:
  port: ${PORT:8765}

spring:
  application:
    name: netflix-zuul-api-gateway-server


zuul:
#  prefix: /api/v1
  routes:
    currency-conversion-service:
      path: /currency-conversion-service/**
      serviceId: currency-conversion-service
    currency-exchange-service:
      path: /currency-exchange-service/**
      serviceId: currency-exchange-service
   

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      
logging:
  file: netflix-zuul-api-gateway-server.log
         