INSERT INTO EXCHANGE_VALUE  (ID,CURRENCY_FROM,CURRENCY_TO,CONVERSION_MULTIPLE ,PORT)
SELECT 1001,'SGD','INR',50,0;
INSERT INTO EXCHANGE_VALUE  (ID,CURRENCY_FROM,CURRENCY_TO,CONVERSION_MULTIPLE ,PORT)
SELECT 1002,'USD','INR',65,0;
INSERT INTO EXCHANGE_VALUE  (ID,CURRENCY_FROM,CURRENCY_TO,CONVERSION_MULTIPLE ,PORT)
SELECT 1003,'GBP','INR',95,0;


